/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DashboardOrientationRouteImport } from './routes/dashboard/orientation'
import { Route as AppTimetableRouteImport } from './routes/app/timetable'
import { Route as AppStudyRouteImport } from './routes/app/study'
import { Route as AppResourcesRouteImport } from './routes/app/resources'
import { Route as AppOrientationRouteImport } from './routes/app/orientation'
import { Route as AppMarketplaceRouteImport } from './routes/app/marketplace'
import { Route as AppDatingRouteImport } from './routes/app/dating'
import { Route as AppClubsRouteImport } from './routes/app/clubs'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppCanteenRouteImport } from './routes/app/canteen'
import { Route as AppAttendanceRouteImport } from './routes/app/attendance'
import { Route as AppAssignmentsRouteImport } from './routes/app/assignments'
import { Route as AppDatingStudyBuddiesRouteImport } from './routes/app/dating/study-buddies'
import { Route as AppDatingStartupRouteImport } from './routes/app/dating/startup'
import { Route as AppDatingSearchRouteImport } from './routes/app/dating/search'
import { Route as AppDatingProfileViewRouteImport } from './routes/app/dating/profile-view'
import { Route as AppDatingProfileRouteImport } from './routes/app/dating/profile'
import { Route as AppDatingNotificationsRouteImport } from './routes/app/dating/notifications'
import { Route as AppDatingMatchesRouteImport } from './routes/app/dating/matches'
import { Route as AppDatingFriendsRouteImport } from './routes/app/dating/friends'
import { Route as AppDatingEventsRouteImport } from './routes/app/dating/events'
import { Route as AppDatingDailyPicksRouteImport } from './routes/app/dating/daily-picks'
import { Route as AppDatingChatRouteImport } from './routes/app/dating/chat'
import { Route as AppAdminDatingRouteImport } from './routes/app/admin/dating'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DashboardOrientationRoute = DashboardOrientationRouteImport.update({
  id: '/dashboard/orientation',
  path: '/dashboard/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppOrientationRoute = AppOrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppDatingRoute = AppDatingRouteImport.update({
  id: '/dating',
  path: '/dating',
  getParentRoute: () => AppRoute,
} as any)
const AppClubsRoute = AppClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCanteenRoute = AppCanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppDatingStudyBuddiesRoute = AppDatingStudyBuddiesRouteImport.update({
  id: '/study-buddies',
  path: '/study-buddies',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingStartupRoute = AppDatingStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingSearchRoute = AppDatingSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingProfileViewRoute = AppDatingProfileViewRouteImport.update({
  id: '/profile-view',
  path: '/profile-view',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingProfileRoute = AppDatingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingNotificationsRoute = AppDatingNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingMatchesRoute = AppDatingMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingFriendsRoute = AppDatingFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingEventsRoute = AppDatingEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingDailyPicksRoute = AppDatingDailyPicksRouteImport.update({
  id: '/daily-picks',
  path: '/daily-picks',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppDatingChatRoute = AppDatingChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppDatingRoute,
} as any)
const AppAdminDatingRoute = AppAdminDatingRouteImport.update({
  id: '/admin/dating',
  path: '/admin/dating',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/canteen': typeof AppCanteenRoute
  '/app/chat': typeof AppChatRoute
  '/app/clubs': typeof AppClubsRoute
  '/app/dating': typeof AppDatingRouteWithChildren
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/orientation': typeof AppOrientationRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/study': typeof AppStudyRoute
  '/app/timetable': typeof AppTimetableRoute
  '/dashboard/orientation': typeof DashboardOrientationRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/dating': typeof AppAdminDatingRoute
  '/app/dating/chat': typeof AppDatingChatRoute
  '/app/dating/daily-picks': typeof AppDatingDailyPicksRoute
  '/app/dating/events': typeof AppDatingEventsRoute
  '/app/dating/friends': typeof AppDatingFriendsRoute
  '/app/dating/matches': typeof AppDatingMatchesRoute
  '/app/dating/notifications': typeof AppDatingNotificationsRoute
  '/app/dating/profile': typeof AppDatingProfileRoute
  '/app/dating/profile-view': typeof AppDatingProfileViewRoute
  '/app/dating/search': typeof AppDatingSearchRoute
  '/app/dating/startup': typeof AppDatingStartupRoute
  '/app/dating/study-buddies': typeof AppDatingStudyBuddiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/canteen': typeof AppCanteenRoute
  '/app/chat': typeof AppChatRoute
  '/app/clubs': typeof AppClubsRoute
  '/app/dating': typeof AppDatingRouteWithChildren
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/orientation': typeof AppOrientationRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/study': typeof AppStudyRoute
  '/app/timetable': typeof AppTimetableRoute
  '/dashboard/orientation': typeof DashboardOrientationRoute
  '/app': typeof AppIndexRoute
  '/app/admin/dating': typeof AppAdminDatingRoute
  '/app/dating/chat': typeof AppDatingChatRoute
  '/app/dating/daily-picks': typeof AppDatingDailyPicksRoute
  '/app/dating/events': typeof AppDatingEventsRoute
  '/app/dating/friends': typeof AppDatingFriendsRoute
  '/app/dating/matches': typeof AppDatingMatchesRoute
  '/app/dating/notifications': typeof AppDatingNotificationsRoute
  '/app/dating/profile': typeof AppDatingProfileRoute
  '/app/dating/profile-view': typeof AppDatingProfileViewRoute
  '/app/dating/search': typeof AppDatingSearchRoute
  '/app/dating/startup': typeof AppDatingStartupRoute
  '/app/dating/study-buddies': typeof AppDatingStudyBuddiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/canteen': typeof AppCanteenRoute
  '/app/chat': typeof AppChatRoute
  '/app/clubs': typeof AppClubsRoute
  '/app/dating': typeof AppDatingRouteWithChildren
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/orientation': typeof AppOrientationRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/study': typeof AppStudyRoute
  '/app/timetable': typeof AppTimetableRoute
  '/dashboard/orientation': typeof DashboardOrientationRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/dating': typeof AppAdminDatingRoute
  '/app/dating/chat': typeof AppDatingChatRoute
  '/app/dating/daily-picks': typeof AppDatingDailyPicksRoute
  '/app/dating/events': typeof AppDatingEventsRoute
  '/app/dating/friends': typeof AppDatingFriendsRoute
  '/app/dating/matches': typeof AppDatingMatchesRoute
  '/app/dating/notifications': typeof AppDatingNotificationsRoute
  '/app/dating/profile': typeof AppDatingProfileRoute
  '/app/dating/profile-view': typeof AppDatingProfileViewRoute
  '/app/dating/search': typeof AppDatingSearchRoute
  '/app/dating/startup': typeof AppDatingStartupRoute
  '/app/dating/study-buddies': typeof AppDatingStudyBuddiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/chat'
    | '/login'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/canteen'
    | '/app/chat'
    | '/app/clubs'
    | '/app/dating'
    | '/app/marketplace'
    | '/app/orientation'
    | '/app/resources'
    | '/app/study'
    | '/app/timetable'
    | '/dashboard/orientation'
    | '/app/'
    | '/app/admin/dating'
    | '/app/dating/chat'
    | '/app/dating/daily-picks'
    | '/app/dating/events'
    | '/app/dating/friends'
    | '/app/dating/matches'
    | '/app/dating/notifications'
    | '/app/dating/profile'
    | '/app/dating/profile-view'
    | '/app/dating/search'
    | '/app/dating/startup'
    | '/app/dating/study-buddies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/canteen'
    | '/app/chat'
    | '/app/clubs'
    | '/app/dating'
    | '/app/marketplace'
    | '/app/orientation'
    | '/app/resources'
    | '/app/study'
    | '/app/timetable'
    | '/dashboard/orientation'
    | '/app'
    | '/app/admin/dating'
    | '/app/dating/chat'
    | '/app/dating/daily-picks'
    | '/app/dating/events'
    | '/app/dating/friends'
    | '/app/dating/matches'
    | '/app/dating/notifications'
    | '/app/dating/profile'
    | '/app/dating/profile-view'
    | '/app/dating/search'
    | '/app/dating/startup'
    | '/app/dating/study-buddies'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/chat'
    | '/login'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/canteen'
    | '/app/chat'
    | '/app/clubs'
    | '/app/dating'
    | '/app/marketplace'
    | '/app/orientation'
    | '/app/resources'
    | '/app/study'
    | '/app/timetable'
    | '/dashboard/orientation'
    | '/app/'
    | '/app/admin/dating'
    | '/app/dating/chat'
    | '/app/dating/daily-picks'
    | '/app/dating/events'
    | '/app/dating/friends'
    | '/app/dating/matches'
    | '/app/dating/notifications'
    | '/app/dating/profile'
    | '/app/dating/profile-view'
    | '/app/dating/search'
    | '/app/dating/startup'
    | '/app/dating/study-buddies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  DashboardOrientationRoute: typeof DashboardOrientationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/orientation': {
      id: '/dashboard/orientation'
      path: '/dashboard/orientation'
      fullPath: '/dashboard/orientation'
      preLoaderRoute: typeof DashboardOrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/timetable': {
      id: '/app/timetable'
      path: '/timetable'
      fullPath: '/app/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study': {
      id: '/app/study'
      path: '/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orientation': {
      id: '/app/orientation'
      path: '/orientation'
      fullPath: '/app/orientation'
      preLoaderRoute: typeof AppOrientationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dating': {
      id: '/app/dating'
      path: '/dating'
      fullPath: '/app/dating'
      preLoaderRoute: typeof AppDatingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clubs': {
      id: '/app/clubs'
      path: '/clubs'
      fullPath: '/app/clubs'
      preLoaderRoute: typeof AppClubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/canteen': {
      id: '/app/canteen'
      path: '/canteen'
      fullPath: '/app/canteen'
      preLoaderRoute: typeof AppCanteenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dating/study-buddies': {
      id: '/app/dating/study-buddies'
      path: '/study-buddies'
      fullPath: '/app/dating/study-buddies'
      preLoaderRoute: typeof AppDatingStudyBuddiesRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/startup': {
      id: '/app/dating/startup'
      path: '/startup'
      fullPath: '/app/dating/startup'
      preLoaderRoute: typeof AppDatingStartupRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/search': {
      id: '/app/dating/search'
      path: '/search'
      fullPath: '/app/dating/search'
      preLoaderRoute: typeof AppDatingSearchRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/profile-view': {
      id: '/app/dating/profile-view'
      path: '/profile-view'
      fullPath: '/app/dating/profile-view'
      preLoaderRoute: typeof AppDatingProfileViewRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/profile': {
      id: '/app/dating/profile'
      path: '/profile'
      fullPath: '/app/dating/profile'
      preLoaderRoute: typeof AppDatingProfileRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/notifications': {
      id: '/app/dating/notifications'
      path: '/notifications'
      fullPath: '/app/dating/notifications'
      preLoaderRoute: typeof AppDatingNotificationsRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/matches': {
      id: '/app/dating/matches'
      path: '/matches'
      fullPath: '/app/dating/matches'
      preLoaderRoute: typeof AppDatingMatchesRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/friends': {
      id: '/app/dating/friends'
      path: '/friends'
      fullPath: '/app/dating/friends'
      preLoaderRoute: typeof AppDatingFriendsRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/events': {
      id: '/app/dating/events'
      path: '/events'
      fullPath: '/app/dating/events'
      preLoaderRoute: typeof AppDatingEventsRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/daily-picks': {
      id: '/app/dating/daily-picks'
      path: '/daily-picks'
      fullPath: '/app/dating/daily-picks'
      preLoaderRoute: typeof AppDatingDailyPicksRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/dating/chat': {
      id: '/app/dating/chat'
      path: '/chat'
      fullPath: '/app/dating/chat'
      preLoaderRoute: typeof AppDatingChatRouteImport
      parentRoute: typeof AppDatingRoute
    }
    '/app/admin/dating': {
      id: '/app/admin/dating'
      path: '/admin/dating'
      fullPath: '/app/admin/dating'
      preLoaderRoute: typeof AppAdminDatingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDatingRouteChildren {
  AppDatingChatRoute: typeof AppDatingChatRoute
  AppDatingDailyPicksRoute: typeof AppDatingDailyPicksRoute
  AppDatingEventsRoute: typeof AppDatingEventsRoute
  AppDatingFriendsRoute: typeof AppDatingFriendsRoute
  AppDatingMatchesRoute: typeof AppDatingMatchesRoute
  AppDatingNotificationsRoute: typeof AppDatingNotificationsRoute
  AppDatingProfileRoute: typeof AppDatingProfileRoute
  AppDatingProfileViewRoute: typeof AppDatingProfileViewRoute
  AppDatingSearchRoute: typeof AppDatingSearchRoute
  AppDatingStartupRoute: typeof AppDatingStartupRoute
  AppDatingStudyBuddiesRoute: typeof AppDatingStudyBuddiesRoute
}

const AppDatingRouteChildren: AppDatingRouteChildren = {
  AppDatingChatRoute: AppDatingChatRoute,
  AppDatingDailyPicksRoute: AppDatingDailyPicksRoute,
  AppDatingEventsRoute: AppDatingEventsRoute,
  AppDatingFriendsRoute: AppDatingFriendsRoute,
  AppDatingMatchesRoute: AppDatingMatchesRoute,
  AppDatingNotificationsRoute: AppDatingNotificationsRoute,
  AppDatingProfileRoute: AppDatingProfileRoute,
  AppDatingProfileViewRoute: AppDatingProfileViewRoute,
  AppDatingSearchRoute: AppDatingSearchRoute,
  AppDatingStartupRoute: AppDatingStartupRoute,
  AppDatingStudyBuddiesRoute: AppDatingStudyBuddiesRoute,
}

const AppDatingRouteWithChildren = AppDatingRoute._addFileChildren(
  AppDatingRouteChildren,
)

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCanteenRoute: typeof AppCanteenRoute
  AppChatRoute: typeof AppChatRoute
  AppClubsRoute: typeof AppClubsRoute
  AppDatingRoute: typeof AppDatingRouteWithChildren
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppOrientationRoute: typeof AppOrientationRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppStudyRoute: typeof AppStudyRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminDatingRoute: typeof AppAdminDatingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCanteenRoute: AppCanteenRoute,
  AppChatRoute: AppChatRoute,
  AppClubsRoute: AppClubsRoute,
  AppDatingRoute: AppDatingRouteWithChildren,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppOrientationRoute: AppOrientationRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppStudyRoute: AppStudyRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminDatingRoute: AppAdminDatingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  DashboardOrientationRoute: DashboardOrientationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
